### ISSUE TITLE
Migrate from Create-React-App to Vite

### ISSUE THREAD

**Issue by vishnuravi** [CS342/2023-PAWS-Dashboard#90]
### Problem

This project was bootstrapped using create-react-app, however, CRA Is no longer being maintained.

### Solution

The application should be migrated to an alternative. I would recommend [Vite](https://vitejs.dev/)

### Additional context

This [article](https://www.robinwieruch.de/vite-create-react-app/) is a good tutorial for migration between CRA and Vite.
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by GIT-Gizmo** [comment]
Hi, I can help with this

**Comment by vishnuravi** [comment]
This issue has been resolved by PR #96.
